### ISSUE TITLE
Copyright infringement

### ISSUE THREAD

**Issue by hlky** [db0/nataili#29]
@db0 @ResidentChief

This project infringes upon my copyright. I am the copyright holder.

**Comment by db0** [comment]
You licensed it as AGPL3. Therefore you licensed everyone to take, modify and share it. Now stop threatening people's livelihoods you scumbag!

**Comment by hlky** [comment]
Stop distributing CSAM.

**Comment by hlky** [comment]
I am the copyright holder. You have no right to use my code.

**Comment by hlky** [comment]
You are a degenerate pedophile.

**Comment by db0** [comment]
I have every right to use and distribute this code, as per the AGPL3 license you added. Now stop spreading terrible libel.
